FROM jenkins/jenkins:lts

USER root

RUN apt-get update && \
    apt-get install -y wget libicu-dev && \
    wget https://dot.net/v1/dotnet-install.sh && \
    chmod +x dotnet-install.sh && \
    ./dotnet-install.sh --channel 10.0 --install-dir /usr/local/dotnet && \
    ln -s /usr/local/dotnet/dotnet /usr/local/bin/dotnet

USER jenkins